# Generated by Django 5.1 on 2024-10-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
